version: "3.7"

networks:
    frontend:
        name: "frontend"
    backend:
        name: "backend"

services:
    frontend:
        build:
            context: ./dockerfiles
            dockerfile: dockerfileFrontend
            args:
                GIT: ${MARKET_LIST_FRONTEND_GIT}
        env_file: 
            - ./.env
        image: market-list-frontend:latest
        container_name: market-list-frontend
        command: npm start
        restart: always
        ports:
            - "${MARKET_LIST_FRONTEND_PORT}:80"
        depends_on:
            - backend
        networks:
            - frontend

    backend:
        build:
            context: ./dockerfiles
            dockerfile: dockerfileBackend
            args:
                GIT: ${MARKET_LIST_BACKEND_GIT}
        env_file: 
            - ./.env
        image: market-list-backend:latest
        container_name: market-list-backend
        command: adonis migration:run && adonis serve
        restart: always
        ports:
            - "${MARKET_LIST_BACKEND_PORT}:3333"
        depends_on:
            - database
        networks:
            - backend

    database:
        image: mysql
        container_name: market-list-database
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        env_file: 
            - ./.env
        ports:
            - "${MARKET_LIST_DATABASE_PORT}:3306"
        networks:
            - backend

    adminer:
        image: adminer
        container_name: market-list-adminer
        restart: always
        env_file: 
            - ./.env
        ports:
            - "${MARKET_LIST_ADMINER_PORT}:8080"