version: "3.7"

networks:
    frontend:
        name: "frontend"
    backend:
        name: "backend"

services:
    # frontend:
    #     build:
    #         context: ./dockerfiles
    #         dockerfile: dockerfileFrontend
    #         args:
    #             GIT: ${MARKET_LIST_FRONTEND_GIT}
    #     env_file: 
    #         - ./.env
    #     image: market-list-frontend:latest
    #     container_name: market-list-frontend
    #     command: npm start
    #     restart: always
    #     ports:
    #         - "${MARKET_LIST_FRONTEND_PORT}:80"
    #     depends_on:
    #         - backend
    #     networks:
    #         - frontend

    backend:
        build:
            context: ./dockerfiles
            dockerfile: dockerfileBackend
            args:
                GIT: ${MARKET_LIST_BACKEND_GIT}
        env_file: 
            - ./.env
        image: market-list-backend:latest
        container_name: market-list-backend
        command: adonis migration:run
        restart: always
        ports:
            - "${MARKET_LIST_BACKEND_PORT}:3333"
        depends_on:
            - database
        networks:
            - backend

    database:
        image: mysql:5.7
        container_name: market-list-database
        restart: always
        env_file: 
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: "${MARKET_LIST_DATABASE_PASSWORD}"
            MYSQL_DATABASE: "${MARKET_LIST_DATABASE_NAME}"
        ports:
            - "${MARKET_LIST_DATABASE_PORT}:3306"
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: market-list-phpmyadmin
        restart: always
        env_file: 
            - ./.env
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "${MARKET_LIST_PHPMYADMIN_PORT}:80"
        depends_on:
            - database
        networks:
            - backend